### ISSUE TITLE
Add Review appears when not logged in

### ISSUE THREAD

**Issue by Sjbrimley26** [chingu-voyage3/fair-rentals#60]
If you exit the app without logging out and then restart the app,  because the _id is still stored in localStorage, the add_review prompt appears before you log in.

**Comment by shoesandsocks** [comment]
I've been seeing that too; just came here to note it... i can think of a partial, but not total fix. The tokens from Auth0 expire after 10 hours, at which point the `isAuthenticated()` check will fail. But the other data stays in localStorage, and sometimes we merely check for_id instead of calling `isAuthenticated()`.

Something that's needed (whether it fixes everything or just some things) is to wipe out everything in localStorage when an `isAuthenticated()` call fails. Easy to do - I might make it part of a bigger re-organization of that file, though. When I saw your other PR, and how it puts `username` in storage "sooner" than the older code, I realized that since switching the Auth0 stuff around to get more info (a preset username and avatar, though some other fields are avaliable too), I should've re-jiggered the "workflow" about what gets stuffed into localstorage when.

**Comment by Sjbrimley26** [comment]
I think the problem I was having had more to do with me calling history.go() too early, but also I see what you mean. I was thinking maybe we could have some sort of exit script to clear localstorage, would that be possible?

**Comment by shoesandsocks** [comment]
(thinking while typing...)
hypothetical: you are logged in, your info is in localStorage. you just logged in so your token is new, will not expire for 9+ hours. the server is stopped and re-started. you click on a page. you should still be logged in, right?

**Comment by Sjbrimley26** [comment]
Yeah now that I think about it the only real exit script that we could trigger would be logging out. Oh it must have been a one time thing but it showed Log In in the corner but still had the addReview form on the location page. Its not doing that now, I'm logged in before and after the server restart

**Comment by shoesandsocks** [comment]
you didn't imagine it; i've definitely seen it more than once. i just can't replicate it now that i'm looking for it.  shrug.

**Comment by shoesandsocks** [comment]
![screen shot 2018-01-17 at 10 13 35 am](https://user-images.githubusercontent.com/17255956/35050224-4e69e7ce-fb70-11e7-8a7c-f1220577c646.png)

**Comment by shoesandsocks** [comment]
happened again. i wasn't watching for it (was doing multi-browser testing) so i'm still not sure how it happened.

**Comment by shoesandsocks** [comment]
wait. maybe because I went straight to a Location page, rather than the front page? will test further.

**Comment by Sjbrimley26** [comment]
Could we just use sessionStorage instead of localStorage?

**Comment by shoesandsocks** [comment]
made a branch that swaps the one for the other. we'll see if that does it.

**Comment by Sjbrimley26** [comment]
![sessionstoragesuccess](https://user-images.githubusercontent.com/28308966/35112317-e9f07922-fc3a-11e7-817d-e3904c52e742.png)
I'm all for using sessionStorage, it seems to have solved the problem. My localstorage still has my username even though its been a few days since I logged on using this work computer.
Are there any downsides to using this method? Other than the user will have to log in every time?

**Comment by shoesandsocks** [comment]
i can't think of any effects other than that. i'll merge this. easy to roll back if we discover a problem

**Comment by Sjbrimley26** [comment]
Closing for now, will open a new one if something pops up.
